### ISSUE TITLE
error while running demo

### ISSUE THREAD

**Issue by nameetas** [Su-informatics-lab/DSTG#11]
Installed /Users/nameetashah/anaconda3/lib/python3.7/site-packages/DSTG-0.0.1-py3.7.egg
Processing dependencies for DSTG==0.0.1
Finished processing dependencies for DSTG==0.0.1
(base) Nameetas-MacBook-Pro:DSTG-main nameetashah$ cd DSTG
(base) Nameetas-MacBook-Pro:DSTG nameetashah$ Rscript convert_data.R
run synthetic data...
(base) Nameetas-MacBook-Pro:DSTG nameetashah$ python train.py
Traceback (most recent call last):
  File "train.py", line 8, in <module>
    from models import DSTG
  File "/Users/nameetashah/Documents/MSCTR/SGI/software/DSTG-main/DSTG/models.py", line 1, in <module>
    from layers import *
  File "/Users/nameetashah/Documents/MSCTR/SGI/software/DSTG-main/DSTG/layers.py", line 4, in <module>
    flags = tf.app.flags
AttributeError: module 'tensorflow' has no attribute 'app'

**Comment by QSong-github** [comment]
It may due to the tensorflow version.
